name: Build and Deploy

on:
  push:
    branches:
      - qa
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

  deploy-qa:
    if: github.ref == 'refs/heads/qa'
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: QA

    steps:
      - name: Deploy to QA
        run: |
          echo "================================"
          echo "Deploying Build to QA"
          echo "Environment : QA"
          echo "Build Successful"
          echo "Deployment Successful"
          echo "================================"

  deploy-production:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: Production

    steps:
      - name: Deploy to Production
        run: |
          echo "================================"
          echo "Deploying Build to Production"
          echo "Environment : Production"
          echo "Deployment Successful"
          echo "================================"
